package ru.vitte.online.helpdesk.service.api;

import ru.vitte.online.helpdesk.dto.IncomingIssueDto;
import ru.vitte.online.helpdesk.dto.IssueDto;

import java.util.List;

public interface IssueService {

    IssueDto createIssue(String email, IncomingIssueDto issueDto);

    IssueDto getIssueById(String email, long issueId, boolean isEmployee);

    List<IssueDto> getAllIssues(String email, boolean isEmployee);

    IssueDto updateIssue(String email, long issueId,boolean isEmployee, IncomingIssueDto issueDto);

    void deleteIssue(String email, long issueId);

    void closeIssue(String email, long issueId, boolean isEmployee);

    void updateIssueWithAutogeneratedAnswer(IncomingIssueDto message);
}
